---
title: "Sesion 2"
author: "Eduardo Martínez"
date: "2025-03-20"
output: html_document
---

```{r}
library(dplyr)
```


## Un centavo de muestreo...

### Muestreo aleatorio simple

```{r}
IDs <- 18:75
muestra_aleatoria <- sample(x = IDs, size = 10)
muestra_aleatoria
```
### Muestreo con reemplazo

```{r}
tipo_escritura <- c("zurdo", "diestro", "ambos")
muestra_con_reemplazo <- sample(x = tipo_escritura, size = 10, replace = TRUE)
muestra_con_reemplazo
```
### Muestreo con ponderaciones

```{r}
tipo_escritura <- c("zurdo", "diestro", "ambos")
ponderaciones <- c(0.2, 0.7, 0.1)
muestra_ponderada <- sample(tipo_escritura, size = 2, prob = ponderaciones)
muestra_ponderada
```
```{r}
tipo_escritura <- c("zurdo", "diestro", "ambos")
ponderaciones <- c(0.2, 0.7, 0.1)
muestra_ponderada <- sample(tipo_escritura, size = 10000, prob = ponderaciones, replace = TRUE)
muestra_ponderada |> table()
```
+ Se puede hacer en un dataframe con la librería `dplyr`

```{r}
tibble(IDs = 18:75) |>
  group_by(IDs) |>
  dplyr::mutate(escritura = sample(tipo_escritura, size = 1, prob = ponderaciones)) |>
  ungroup()
```

### Muestreo estratificado

+ La función by() aplica una función a un subconjunto específico de un data frame basado en uno o más factores.

```{r}
datos <- data.frame(
  grupo = c("1o", "1o", "1o", "1o", "2o", "2o", "2o", "3o", "3o"),
  estudiante = c("Ariel", "Enrique", "Elena", "Fenando", "Julian",
                 "Eugenia", "Rocio", "David", "Felipe"),
  calificacion = c(85, 90, 78, 88, 92, 95, 75, 68, 100)
)

datos
```

```{r}
calif_promedio <- by(data = datos$calificacion, INDICES = datos$grupo, FUN = mean)
calif_promedio
```
```{r}
calif_promedio |> str()
```

```{r}
by(data = datos$calificacion,
   INDICES = datos$grupo,
   FUN = function(x) sample(x, size = 2)
    )
```

```{r}
by(data = datos$calificacion,
   INDICES = datos$grupo,
   FUN = function(x) sample(x, size = 2)
    ) |> unlist()
```
```{r}
library(ggplot2) # Visualizaciones
library(ggExtra) # Visualizaciones
library(corrplot) # Visualizaciones de la matriz de correlación
library(dplyr) # Operaciones entre dataframes
library(magrittr) # Algunos operadores de asignación
library(palmerpenguins) # El dataset de los pingüinitos
library(visdat) # Visualización de los datos faltantes
library(skimr) # Para generer métricas
library(janitor) # Para embellecer
library(moments) # Calcular la kurtosis y la skewness
library(hexbin) # Auxiliar para visualización
```

+ Vamos a hacer unas graficas sencillas

```{r}
datos <- ggplot2::msleep
```

```{r}
datos |> ggplot() +
  geom_histogram(aes(x = sleep_total, y = ..density..),
                 bins = 40, fill = "blue", alpha = 0.5) +
  geom_density(aes(x = sleep_total), color = "red", size = 0.5) +
  theme_light()
```

```{r}
datos |> ggplot() +
  geom_histogram(aes(x = sleep_total, y = ..density..),
                 bins = 40, fill = "blue", alpha = 0.5) +
  geom_density(aes(x = sleep_total), color = "red", size = 0.5) +
  facet_wrap(~vore) +
  theme_light()
```


```{r}
datos |> dplyr::select(where(is.numeric)) |>
  cor(use = "complete.obs") |> corrplot.mixed(order = 'AOE')
```

```{r}
datos |> dplyr::select(where(is.numeric)) |>
  cor(use = "complete.obs")
```

```{r}
# Correlación (Relación lineal de toda la vida)
datos |> dplyr::select(where(is.numeric)) |>
  cor(use = "complete.obs", method = "pearson") |> corrplot.mixed(order = 'AOE')
```

```{r}
# Correlación (Relación monótona)
datos |> dplyr::select(where(is.numeric)) |>
  cor(use = "complete.obs", method = "spearman") |> corrplot.mixed(order = 'AOE')
```


```{r}
datos |> ggplot() +
  geom_point(aes(x = sleep_total, y = brainwt)) +
  theme_light()
```

```{r}
graf <- datos |> ggplot(aes(x = sleep_total, y = brainwt)) +
  geom_point() +
  theme_light()

graf <- ggMarginal(graf, type = "histogram")
```

```{r}
graf
```

```{r}
graf <- datos |> ggplot(aes(x = sleep_total, y = brainwt, color = vore)) +
  geom_point() +
  theme_light()

graf <- ggMarginal(graf, type = "histogram",
                   groupColour = TRUE,
                   groupFill = TRUE)
```

```{r}
graf
```


```{r}
datos |> ggplot() +
  geom_point(aes(x = sleep_total, y = brainwt, color = vore)) +
  facet_wrap(~vore) +
  theme_light()
```



```{r}
datos |> ggplot() +
  geom_hex(aes(x = sleep_total, y = brainwt), bins = 20, color = "white") +
  theme_light()
```

```{r}
datos |> ggplot() +
  geom_hex(aes(x = sleep_total, y = brainwt), bins = 20) +
  scale_fill_viridis_c() +
  theme_light()
```



```{r}
datos |> ggplot() +
  geom_density_2d(aes(x = sleep_total, y = brainwt))
```
```{r}
datos |> ggplot() +
  geom_density_2d(aes(x = sleep_total, y = brainwt), binwidth = 0.04)
```

```{r}
datos |> ggplot() +
  geom_density_2d(aes(x = sleep_total, y = brainwt), binwidth = 0.04) +
  facet_wrap(~vore) +
  theme_light()
```
```{r}
datos |> ggplot() +
  geom_density_2d(aes(x = sleep_total, y = brainwt), binwidth = 0.05) +
  facet_wrap(~conservation) +
  theme_light()
```

```{r}
datos |> ggplot() +
  geom_density_2d(aes(x = sleep_rem, y = brainwt), binwidth = 0.04) +
  facet_wrap(~vore) +
  theme_light()
```

```{r}
datos |> ggplot() +
  geom_density_2d(aes(x = sleep_cycle, y = brainwt)) +
  facet_wrap(~vore) +
  theme_light()
```

```{r}
datos |> ggplot() +
  geom_density_2d(aes(x = sleep_cycle, y = bodywt)) +
  facet_wrap(~vore) +
  theme_light()
```


```{r}
library(esquisse)
library(palmerpenguins)
```

```{r}
datos <- palmerpenguins::penguins
```

```{r}
esquisser(datos)
```

```{r}
library(GWalkR)
```


```{r}
gwalkr(datos)
```

